config/routes.rb
Rails.application.routes.draw do
  
  root "listings#index"
  devise_for :users
  resources :listings
  resources :conversations, only: [:index, :create]
  resources :messages, only: [:index, :create]
  resources :bookings
  
  get '/support' => 'support#new'
  post '/support' => 'support#create'
  
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id                 :integer          not null, primary key
#  title              :string
#  street_address     :string
#  city               :string
#  country_code       :string
#  bed_count          :integer
#  bedroom_count      :integer
#  bathroom_count     :integer
#  description        :text
#  night_fee_cents    :integer
#  cleaning_fee_cents :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  host_id            :integer
#  latitude           :decimal(10, 6)
#  longitude          :decimal(10, 6)
#
class Listing < ApplicationRecord
  validates :title, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :country_code, presence: {message: -> (listing, data) { "No country for code: #{listing.country_code}"}}
  validates :bed_count, numericality: {greater_than: 0}
  validates :bedroom_count, numericality: {greater_than: 0}
  validates :bathroom_count, numericality: {greater_than: 0}
  validates :night_fee_cents, numericality: {greater_than: 0}
  
  has_many :conversations
  belongs_to :host, class_name: 'User'
  
  geocoded_by :full_address   # can also be an IP address
  after_validation :geocode #, if: ->(obj){ obj.full_address.present? and obj.full_address_changed? } # auto-fetch
  # coordinates

  monetize :night_fee_cents
  monetize :cleaning_fee_cents
  
  def country
    ISO3166::Country.new(country_code.upcase)
  end
  
  def full_address
    return nil if country.nil?
    "#{street_address}, #{city}, #{country.name}"
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @booking = Booking.new(check_in_at: Date.today, listing_id: @listing.id, guest_id: current_user.id)
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :street_address, :city, :country_code, :bed_count, :bedroom_count, :bathroom_count, :description, :night_fee_cents, :cleaning_fee_cents)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :listing_title %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address, id: :listing_street_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :listing_city %>
  </div>

  <div class="field">
    <%= form.label :country_code %>
    <%= form.text_field :country_code, id: :listing_country_code %>
  </div>

  <div class="field">
    <%= form.label :bed_count %>
    <%= form.number_field :bed_count, id: :listing_bed_count %>
  </div>

  <div class="field">
    <%= form.label :bedroom_count %>
    <%= form.number_field :bedroom_count, id: :listing_bedroom_count %>
  </div>

  <div class="field">
    <%= form.label :bathroom_count %>
    <%= form.number_field :bathroom_count, id: :listing_bathroom_count %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :listing_description %>
  </div>

  <div class="field">
    <%= form.label :night_fee_cents %>
    <%= form.number_field :night_fee_cents, id: :listing_night_fee_cents %>
  </div>

  <div class="field">
    <%= form.label :cleaning_fee_cents %>
    <%= form.number_field :cleaning_fee_cents, id: :listing_cleaning_fee_cents %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing, class: 'btn btn-success' %>
<%= link_to 'Back', listings_path, class: 'btn btn-success' %>

app/views/listings/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <h1 class="mt-3">Rails BnB</h1>
    </div>
    <div class="col">
      <nav>
        <% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, class: 'btn btn-warning', method: :delete %>
        <% else %>
          <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary' %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary' %>
        <% end %>
      </nav>
    </div>
  </div>
</div>

<h1>Listings</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Street address</th>
      <th>City</th>
      <th>Country</th>
      <th>Bed count</th>
      <th>Bedroom count</th>
      <th>Bathroom count</th>
      <th>Description</th>
      <th>Night fee</th>
      <th>Cleaning fee</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= link_to 'Edit', edit_listing_path(listing), class: 'btn btn-warning btn-sm' %></td>
        <td><%= link_to listing.title, listing, class: 'btn btn-success btn-sm' %></td>
        <td><%= listing.street_address %></td>
        <td><%= listing.city %></td>
        <td><%= listing.country.name %></td>
        <td><%= listing.bed_count %></td>
        <td><%= listing.bedroom_count %></td>
        <td><%= listing.bathroom_count %></td>
        <td><%= listing.description %></td>
        <td><%= listing.night_fee.format %></td>
        <td><%= listing.cleaning_fee.format %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn
        btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path, class: 'btn btn-warning' %>
<%= link_to 'Support Email', support_path, class: 'btn btn-success' %>
<%= link_to 'Bookings', bookings_path, class: 'btn btn-success' %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path, class: 'btn btn-success' %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  Per Night:
  <%= @listing.night_fee.format %>
</p>

<%= form_with(model: @booking, local: true) do |form| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.submit 'Book', class: 'wide btn btn-warning' %>

  <%= form.hidden_field :listing_id %>
  <%= form.hidden_field :guest_id %>

  <div class="field">
    <%= form.label :check_in_at %>
    <%= form.date_field :check_in_at %>
  </div>

  <div class="field">
    <%= form.label :check_out_at %>
    <%= form.date_field :check_out_at %>
  </div>

  <div class="field">
    <%= form.label :guest_count %>
    <%= form.number_field :guest_count %>
  </div>

<% end %>


<p>
  <strong>Street address:</strong>
  <%= @listing.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @listing.country.name %>
</p>

<p>
  <strong>Coords:</strong>
  <%= @listing.latitude %>, <%= @listing.longitude %>
</p>

<p>
  <strong>Bed count:</strong>
  <%= @listing.bed_count %>
</p>

<p>
  <strong>Bedroom count:</strong>
  <%= @listing.bedroom_count %>
</p>

<p>
  <strong>Bathroom count:</strong>
  <%= @listing.bathroom_count %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Cleaning fee:</strong>
  <%= @listing.cleaning_fee.format %>
</p>

<%= button_to 'Messages', conversations_path(listing: @listing, method: :post), class: 'btn btn-warning' %>
<%= link_to 'Edit', edit_listing_path(@listing), class: 'btn btn-warning' %>
<%= link_to 'Back', listings_path, class: 'btn btn-success' %>