config/routes.rb
Rails.application.routes.draw do
  
  root "listings#index"
  devise_for :users
  resources :listings
  resources :conversations, only: [:index, :create]
  resources :messages, only: [:index, :create]
  resources :bookings
  
  get '/support' => 'support#new'
  post '/support' => 'support#create'
  
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  listing_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  has_many :messages
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :create]

  # GET /conversations
  # GET /conversations.json
  def index
    @listing = Listing.find(params[:listing])
    if current_user == @listing.host
      @conversations = Conversation.where(listing_id: params[:listing])
      @messages = Message.where(read: :false)
    else
      @conversations = Conversation.where(user: current_user).where(listing_id: params[:listing])
    end
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @listing = Listing.find(params[:listing])
    if current_user == @listing.host
      # I am a lister so choose a conversation with user from list
      redirect_to(conversations_path(listing: @listing)) && return
    else
      # I am a customer looking to book
      @conv = Conversation.where(listing: @listing).where(user: current_user)
    end
    
    if @conv.first.present?
      # I have a conversation with host already
      redirect_to(messages_path(conversation_id: @conv.first.id)) && return
    end
    
    @conversation = Conversation.new(user: current_user, listing: @listing)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to messages_path(conversation_id: @conversation.id),
                                  notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:user_id, :listing)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_with(model: conversation, local: true) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :conversation_user_id %>
  </div>

  <div class="field">
    <%= form.label :listing %>
    <%= form.text_field :listing, id: :conversation_listing %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<h1>Conversations</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>User</th>
      <th>Listing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.user.email %></td>
        <td><%= conversation.listing.title %></td>
        <td><%= link_to 'Messages', messages_path(conversation_id: conversation.id), class: 'btn
        btn-warning' %></td>
      </tr>
        <% @messages.each do |message| %>
          <% if message.conversation_id == conversation.id %>
            <tr><td><%= message.content %></td></tr>
          <% end %>
        <% end %>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', listing_path(@conversations.first.listing), class: 'btn btn-success' %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<h1>Conversation</h1>
<div id="messages">
  <%= render @messages %>
</div>
<form>
  <label>Say something:</label>
  <br>
  <input type="text" data-behavior="conversation_speaker">
</form>
<%= link_to 'Back', conversations_path, class: 'btn btn-success' %>