config/routes.rb
Rails.application.routes.draw do
  
  root "listings#index"
  devise_for :users
  resources :listings
  resources :conversations, only: [:index, :create]
  resources :messages, only: [:index, :create]
  resources :bookings
  
  get '/support' => 'support#new'
  post '/support' => 'support#create'
  
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :check_in_at, presence: true
  validates :check_out_at, presence: true
  validate :validates_date
  validates :guest_count, numericality: {greater_than: 0}
  
  belongs_to :listing
  belongs_to :guest, class_name: 'User'
  
  
  
  private
  
    def validates_date
      if check_in_at.present?
        errors.add(:check_in_at, "can't be in the past") if check_in_at < Date.today
        errors.add(:check_out_at, "can't be before or equal to check in date") if check_out_at.present? &&
            check_out_at <= check_in_at
      end
    end
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    #@listing = Listing.find(params[:listing_id])
    #@booking = Booking.new(listing: @listing)
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @listing = Listing.find(booking_params[:listing_id])
    @new_booking = Booking.new(booking_params)

    respond_to do |format|
      if @new_booking.save
        format.html { redirect_to @listing, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @new_booking }
      else
        format.html { redirect_to listing_path(@listing) }
        format.json { render json: @new_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:listing_id, :guest_id, :check_in_at, :check_out_at, :guest_count)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :guest %>
    <%= form.text_field :guest, id: :booking_guest %>
  </div>

  <div class="field">
    <%= form.label :check_in_at %>
    <%= form.date_select :check_in_at, id: :booking_check_in_at %>
  </div>

  <div class="field">
    <%= form.label :check_out_at %>
    <%= form.date_select :check_out_at, id: :booking_check_out_at %>
  </div>

  <div class="field">
    <%= form.label :guest_count %>
    <%= form.number_field :guest_count, id: :booking_guest_count %>
  </div>

  <div class="field">
    <%= form.label :charge_identifier %>
    <%= form.text_field :charge_identifier, id: :booking_charge_identifier %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking, class: 'btn btn-success'  %> |
<%= link_to 'Back', bookings_path, class: 'btn btn-success'  %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Listing</th>
      <th>Guest</th>
      <th>Check in at</th>
      <th>Check out at</th>
      <th>Guest count</th>
      <th>Charge identifier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.listing.title %></td>
        <td><%= booking.guest.email %></td>
        <td><%= booking.check_in_at %></td>
        <td><%= booking.check_out_at %></td>
        <td><%= booking.guest_count %></td>
        <td><%= booking.charge_identifier %></td>
        <td><%= link_to 'Show', booking, class: 'btn btn-success'  %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn
        btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', listings_path, class: 'btn btn-success' %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', listing_path(@listing), class: 'btn btn-success' %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Listing:</strong>
  <%= @booking.listing.title %>
</p>

<p>
  <strong>Guest:</strong>
  <%= @booking.guest.email %>
</p>

<p>
  <strong>Check in at:</strong>
  <%= @booking.check_in_at %>
</p>

<p>
  <strong>Check out at:</strong>
  <%= @booking.check_out_at %>
</p>

<p>
  <strong>Guest count:</strong>
  <%= @booking.guest_count %>
</p>

<p>
  <strong>Charge identifier:</strong>
  <%= @booking.charge_identifier %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking), class: 'btn btn-warning' %>
<%= link_to 'Back', bookings_path, class: 'btn btn-success'  %>