config/routes.rb
Rails.application.routes.draw do
  
  root "listings#index"
  devise_for :users
  resources :listings
  resources :conversations, only: [:index, :create]
  resources :messages, only: [:index, :create]
  resources :bookings
  
  get '/support' => 'support#new'
  post '/support' => 'support#create'
  
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
  def new
    @error_messages = []
  end
  
  def create
    from_email = params[:email]
    message = params[:message]
    
    @error_messages = []
    @error_messages << 'Please enter your email' if from_email.blank?
    @error_messages << 'Please enter your message' if message.blank?
    
    if @error_messages.empty?
      # send message
      SupportMailer.contact_support(from_email, message).deliver_now
      render :success
    else
      # show errors
      render :new
    end
  end
end

app/helpers/support_helper.rb
module SupportHelper
end

app/views/support/new.html.erb
<h1>Support</h1>

<p>Please message our support team here:</p>

<%= form_with(url: support_url, local: true ) do |f| %>
  <% unless @error_messages.empty? %>
    <% @error_messages.each do |message| %>
      <p><%= message %> </p>
      <% end %>
  <% end %>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :message %>
    <%= f.text_area :message, rows: 6 %>
  </div>

  <%= f.button 'Send', class: 'btn btn-warning'%>
<% end %>
<%= link_to 'Back', listings_path, class: 'btn btn-success' %>

app/views/support/success.html.erb
<h1>Support</h1>

<p>Your message has been successfully received.</p>

<%= link_to 'Back', support_path, class: 'btn btn-success' %>